### ISSUE TITLE
implement turn logic

### ISSUE THREAD

**Issue by kswang2400** [kswang2400/avalon#9]
turn logic todo:
- [x] quest master suggests team -- https://github.com/kswang2400/avalon/pull/28
- [x] game users vote whether or not the team goes on a quest -- https://github.com/kswang2400/avalon/pull/33
- [x] if failed, pass quest master to next user and restart - https://github.com/kswang2400/avalon/pull/37
- [x] if pass, team must go on quest
    - [x] quest members vote `succeed` or `fail` (are good guys required to vote `succeed`?)
 - [x] publish quest results -- https://github.com/kswang2400/avalon/pull/39

/turn

**Comment by chidinmae** [comment]
Begin with an automatic game

**Comment by kswang2400** [comment]
https://github.com/kswang2400/avalon/pull/28
